import { execFileSync } from 'node:child_process';
import { cp, mkdir, rm } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  cssDeclarations,
  digestDirectory,
  filesIn,
  flatten,
  readJson,
  resolveReferences,
  writeText,
} from './lib.mjs';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const root = resolve(scriptDirectory, '..');
const generatedBrand = join(root, 'brand', 'generated');
const distribution = join(root, 'packages', 'design', 'dist');
const assetDistribution = join(distribution, 'assets');

const primitives = await readJson(join(root, 'tokens', 'primitives.json'));
const semanticSource = await readJson(join(root, 'tokens', 'semantic.json'));
const componentSource = await readJson(join(root, 'tokens', 'components.json'));
const brandSource = await readJson(join(root, 'tokens', 'brand.json'));
const geometry = await readJson(join(root, 'brand', 'source', 'geometry.json'));
const packageJson = await readJson(join(root, 'package.json'));

const semantic = resolveReferences(semanticSource, primitives);
const components = resolveReferences(componentSource, primitives);
const brand = resolveReferences(brandSource, primitives);

/* Font stacks quote family names; SVG attributes are already double-quoted. */
const svgFont = (stack) => stack.replaceAll('"', "'");
const sansStack = svgFont(primitives.font.sans);
const monoStack = svgFont(primitives.font.mono);

await rm(generatedBrand, { recursive: true, force: true });
await rm(distribution, { recursive: true, force: true });
await mkdir(generatedBrand, { recursive: true });
await mkdir(distribution, { recursive: true });

function tokenCss() {
  const primitiveEntries = flatten(primitives);
  const componentEntries = flatten(components);
  return `/*
 * Generated by @open-e2ee/design. Do not edit directly.
 * Source: tokens/*.json
 */

:root {
  color-scheme: light;
${cssDeclarations(primitiveEntries)}

${cssDeclarations(flatten(semantic.light))}

${cssDeclarations(componentEntries)}
}

:root.dark {
  color-scheme: dark;
${cssDeclarations(flatten(semantic.dark))}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --oe-duration-fast: 0.01ms;
    --oe-duration-normal: 0.01ms;
    --oe-duration-slow: 0.01ms;
  }
}
`;
}

function tailwindCss() {
  const declarations = (entries) =>
    entries.map(([name, value]) => `  --${name}: ${value};`).join('\n');
  const colors = flatten(primitives.color).map(([name, value]) => [
    `color-oe-${name}`,
    value,
  ]);
  const radii = flatten(primitives.radius).map(([name, value]) => [
    `radius-brand-${name}`,
    value,
  ]);
  const semanticColors = Object.keys(semantic.light)
    .filter((key) => !key.startsWith('shadow-'))
    .map((key) => [`color-${key}`, `var(--oe-${key})`]);
  const semanticShadows = [
    ['shadow-brand-sm', 'var(--oe-shadow-sm)'],
    ['shadow-brand-md', 'var(--oe-shadow-md)'],
  ];

  return `/*
 * Generated Tailwind CSS v4 adapter. Import after "tailwindcss".
 */

@import "./tokens.css";

@custom-variant dark (&:where(.dark, .dark *));

@theme static {
${declarations(colors)}
  --font-brand-sans: ${primitives.font.sans};
  --font-brand-serif: ${primitives.font.serif};
  --font-brand-mono: ${primitives.font.mono};
${declarations(radii)}
}

@theme inline {
${declarations(semanticColors)}
${declarations(semanticShadows)}
}
`;
}

const fontsCss = `/*
 * Optional self-hosted OpenE2EE typefaces.
 * Imported from package dependencies; no third-party font request is made.
 *
 * Public Sans is the only family on the critical path. Newsreader (editorial
 * prose) and JetBrains Mono (code, identifiers, metadata) are worth preloading
 * per route rather than globally.
 */

@import "@fontsource-variable/public-sans";
@import "@fontsource-variable/newsreader";
@import "@fontsource-variable/jetbrains-mono";
`;

/*
 * The wordmark ships as live text, not as outlines: the weight contrast
 * between "Open" and "E2EE" is the whole concept, and a variable font renders
 * it at any size without shipping a second asset. See DESIGN.md for the four
 * craft corrections that a later outlined wordmark.svg should apply.
 */
const wordmarkCss = `/*
 * Generated by @open-e2ee/design. Do not edit directly.
 * Source: tokens/components.json
 *
 * Usage: <span class="oe-wordmark"><span>Open</span><span>E2EE</span></span>
 */

@import "./tokens.css";

.oe-wordmark {
  font-family: var(--oe-wordmark-font-family);
  font-style: normal;
  white-space: nowrap;
  font-synthesis-weight: none;
}

.oe-wordmark > :first-child {
  font-weight: var(--oe-wordmark-open-weight);
  letter-spacing: var(--oe-wordmark-open-tracking);
}

.oe-wordmark > :last-child {
  font-weight: var(--oe-wordmark-e2ee-weight);
  letter-spacing: var(--oe-wordmark-e2ee-tracking);
}

/*
 * Below 14px the weight contrast stops resolving and starts reading as a
 * rendering bug, so the wordmark reverts to one uniform weight.
 */
.oe-wordmark-small > :first-child,
.oe-wordmark-small > :last-child {
  font-weight: var(--oe-wordmark-small-weight);
  letter-spacing: var(--oe-wordmark-small-tracking);
}
`;

const themeModule = `const STORAGE_KEY = 'oe-theme';
const THEMES = new Set(['light', 'dark', 'system']);

function systemPrefersDark() {
  return typeof matchMedia === 'function' &&
    matchMedia('(prefers-color-scheme: dark)').matches;
}

export function resolveTheme(preference = 'system') {
  return preference === 'dark' ||
    (preference === 'system' && systemPrefersDark())
    ? 'dark'
    : 'light';
}

export function applyTheme(preference = 'system', root = document.documentElement) {
  const resolved = resolveTheme(preference);
  root.classList.toggle('dark', resolved === 'dark');
  root.style.colorScheme = resolved;
  return resolved;
}

export function getStoredTheme(storage = localStorage) {
  const value = storage.getItem(STORAGE_KEY) ?? 'system';
  return THEMES.has(value) ? value : 'system';
}

export function applyStoredTheme(options = {}) {
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  return applyTheme(getStoredTheme(storage), root);
}

export function setTheme(preference, options = {}) {
  if (!THEMES.has(preference)) {
    throw new TypeError('Theme must be "light", "dark", or "system".');
  }
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  storage.setItem(STORAGE_KEY, preference);
  return applyTheme(preference, root);
}

export function watchSystemTheme(options = {}) {
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  const query = matchMedia('(prefers-color-scheme: dark)');
  const listener = () => {
    if (getStoredTheme(storage) === 'system') applyTheme('system', root);
  };
  query.addEventListener('change', listener);
  return () => query.removeEventListener('change', listener);
}

export { STORAGE_KEY, THEMES };
`;

await writeText(join(distribution, 'css', 'tokens.css'), tokenCss());
await writeText(join(distribution, 'css', 'tailwind.css'), tailwindCss());
await writeText(join(distribution, 'css', 'fonts.css'), fontsCss);
await writeText(join(distribution, 'css', 'wordmark.css'), wordmarkCss);
await writeText(join(distribution, 'theme.mjs'), themeModule);
await writeText(
  join(distribution, 'index.mjs'),
  `export * from './theme.mjs';\n`,
);
await writeText(
  join(distribution, 'theme.d.ts'),
  `export type ThemePreference = 'light' | 'dark' | 'system';
export type ResolvedTheme = 'light' | 'dark';
export interface ThemeOptions {
  storage?: Storage;
  root?: HTMLElement;
}
export declare function resolveTheme(preference?: ThemePreference): ResolvedTheme;
export declare function applyTheme(
  preference?: ThemePreference,
  root?: HTMLElement,
): ResolvedTheme;
export declare function getStoredTheme(storage?: Storage): ThemePreference;
export declare function applyStoredTheme(options?: ThemeOptions): ResolvedTheme;
export declare function setTheme(
  preference: ThemePreference,
  options?: ThemeOptions,
): ResolvedTheme;
export declare function watchSystemTheme(options?: ThemeOptions): () => void;
export declare const STORAGE_KEY: 'oe-theme';
export declare const THEMES: ReadonlySet<ThemePreference>;
`,
);
await writeText(
  join(distribution, 'index.d.ts'),
  `export * from './theme.js';\n`,
);
await writeText(
  join(distribution, 'tokens.json'),
  JSON.stringify({ primitives, semantic, components, brand, geometry }, null, 2),
);

/*
 * The Opaque Carrier mark.
 *
 * Two hollow carrier brackets hold one solid payload that touches neither of
 * them. Everything is a single fill color: no strokes, no radii, no gradients,
 * no second tone. The full mark carries the shear; the optical variant drops it
 * so the silhouette survives at favicon sizes.
 */

const markSizes = [16, 24, 32, 48, 64, 128, 256, 512, 1024];

function variantForSize(size) {
  if (size < geometry.minimumSize) {
    throw new Error(`The mark is not reproduced below ${geometry.minimumSize} px.`);
  }
  return size <= geometry.smallMaximumSize ? 'optical' : 'full';
}

function markPaths(variant) {
  const { carrierLeftPath, carrierRightPath, payloadPath } = geometry[variant];
  return [carrierLeftPath, carrierRightPath, payloadPath];
}

const markDescription = {
  full:
    'Two open carrier brackets holding a solid sheared payload. The payload ' +
    'touches neither bracket.',
  optical:
    'Two open carrier brackets holding a solid square payload. Small-size ' +
    'optical variant, drawn without the shear.',
};

function markMarkup(fill, variant, indent = '  ') {
  return markPaths(variant)
    .map((path) => `${indent}<path d="${path}" fill="${fill}"/>`)
    .join('\n');
}

const forcedColors = `    @media (forced-colors: active) {
      path { fill: CanvasText; }
    }`;

function standaloneSvg({ mode, fill, variant, background }) {
  const sizeLabel = variant === 'optical' ? ' small-size' : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${geometry.viewBox}" role="img" aria-labelledby="title desc">
  <title id="title">OpenE2EE${sizeLabel} mark — ${mode}</title>
  <desc id="desc">${markDescription[variant]}</desc>
  <metadata>Mark: opaque-carrier; variant: ${variant}; mode: ${mode}; intended background: ${background}; generated by @open-e2ee/design ${packageJson.version}.</metadata>
  <style>
${forcedColors}
  </style>
${markMarkup(fill, variant)}
</svg>
`;
}

function adaptiveSvg(variant, { title, width = 512 } = {}) {
  const sizeLabel = variant === 'optical' ? ' small-size' : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${width}" viewBox="${geometry.viewBox}" role="img" aria-labelledby="title desc">
  <title id="title">${title ?? `Adaptive OpenE2EE${sizeLabel} mark`}</title>
  <desc id="desc">${markDescription[variant]} The fill follows the active color scheme.</desc>
  <style>
    :root { --oe-mark: ${brand.modes.light.mark}; }
    @media (prefers-color-scheme: dark) {
      :root { --oe-mark: ${brand.modes.dark.mark}; }
    }
${forcedColors}
  </style>
${markMarkup('var(--oe-mark)', variant)}
</svg>
`;
}

const svgDirectory = join(generatedBrand, 'svg');
const pngDirectory = join(generatedBrand, 'png');
await mkdir(svgDirectory, { recursive: true });
await mkdir(pngDirectory, { recursive: true });

const variantSvgPath = {};
for (const variant of ['full', 'optical']) {
  const suffix = variant === 'optical' ? '-small' : '';
  for (const [mode, colors] of Object.entries(brand.modes)) {
    const path = join(svgDirectory, `open-e2ee-mark-${mode}${suffix}.svg`);
    await writeText(
      path,
      standaloneSvg({
        mode: `${mode} mode`,
        fill: colors.mark,
        variant,
        background: colors.background,
      }),
    );
    variantSvgPath[`${mode}-${variant}`] = path;
  }

  await writeText(
    join(svgDirectory, `open-e2ee-mark-mono${suffix}.svg`),
    standaloneSvg({
      mode: 'monochrome',
      fill: 'currentColor',
      variant,
      background: 'any',
    }),
  );
  await writeText(
    join(generatedBrand, `open-e2ee-mark-adaptive${suffix}.svg`),
    adaptiveSvg(variant),
  );
}

await writeText(
  join(generatedBrand, 'open-e2ee-favicon.svg'),
  adaptiveSvg('optical', { title: 'OpenE2EE', width: 32 }),
);

const pngVariants = {};
for (const size of markSizes) {
  const variant = variantForSize(size);
  pngVariants[size] = variant;
  const outputDirectory = join(pngDirectory, String(size));
  await mkdir(outputDirectory, { recursive: true });
  for (const mode of Object.keys(brand.modes)) {
    execFileSync('rsvg-convert', [
      '--width',
      String(size),
      '--height',
      String(size),
      '--output',
      join(outputDirectory, `open-e2ee-mark-${mode}.png`),
      variantSvgPath[`${mode}-${variant}`],
    ]);
  }
}

/*
 * Presentation sheet: both modes, and the size rule drawn rather than stated.
 */
function sheetSvg() {
  const width = 1240;
  const height = 680;
  const sampleSizes = [16, 24, 32, 64];
  const cards = Object.entries(brand.modes).map(([mode, colors], index) => {
    const x = 40 + index * 600;
    let cursor = 48;
    const samples = sampleSizes.map((size) => {
      const variant = variantForSize(size);
      const scale = size / 512;
      const markup = `
      <g transform="translate(${cursor} ${64 - size}) scale(${scale})">
${markMarkup(colors.mark, variant, '        ')}
      </g>
      <text x="${cursor}" y="88" fill="${colors.mark}" font-family="${monoStack}" font-size="13" opacity="0.72">${size}px ${variant}</text>`;
      cursor += Math.max(size, 74) + 34;
      return markup;
    });
    return `
  <g transform="translate(${x} 40)">
    <rect width="560" height="600" fill="${colors.background}"/>
    <g transform="translate(120 40) scale(0.625)">
${markMarkup(colors.mark, 'full', '      ')}
    </g>
    <g transform="translate(40 424)">${samples.join('')}
    </g>
    <text x="40" y="558" fill="${colors.label}" font-family="${monoStack}" font-size="20" font-weight="600" letter-spacing="1.4">${mode.toUpperCase()} MODE</text>
  </g>`;
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc">
  <title id="title">The OpenE2EE mark in light and dark modes</title>
  <desc id="desc">The full mark above the size rule: the optical variant from 16 to 31 px, the full mark from 32 px.</desc>
  <rect width="${width}" height="${height}" fill="${brand.sheet.background}"/>${cards.join('')}
</svg>
`;
}

await writeText(join(generatedBrand, 'open-e2ee-mark-sheet.svg'), sheetSvg());
execFileSync('rsvg-convert', [
  '--width',
  '1240',
  '--height',
  '680',
  '--output',
  join(generatedBrand, 'open-e2ee-mark-sheet.png'),
  join(generatedBrand, 'open-e2ee-mark-sheet.svg'),
]);

/*
 * Social preview (1280x640): canvas, mark, wordmark, one description line, and
 * a manifest plate bleeding off the right edge. The plate is an object store
 * drawn in the diagram grammar — outlined carrier, opaque parcels, brass
 * metadata ticks on every parcel — annotated with what this package actually
 * ships.
 */
function slabPath({ x, y, width, height, shear = 0 }) {
  return `M${x + shear} ${y} L${x + width + shear} ${y} L${x + width} ${y + height} L${x} ${y + height} Z`;
}

function metadataTicks({ x, y, count, fill, spacing = 16, length = 10 }) {
  return Array.from(
    { length: count },
    (_, index) =>
      `<rect x="${x + index * spacing}" y="${y - length - 4}" width="2" height="${length}" fill="${fill}"/>`,
  ).join('');
}

function carrierBrackets({ x, y, width, height, thickness, arm, fill }) {
  const right = x + width;
  return [
    `M${x} ${y} H${x + arm} V${y + thickness} H${x + thickness} V${y + height - thickness} H${x + arm} V${y + height} H${x} Z`,
    `M${right} ${y} H${right - arm} V${y + thickness} H${right - thickness} V${y + height - thickness} H${right - arm} V${y + height} H${right} Z`,
  ]
    .map((path) => `<path d="${path}" fill="${fill}"/>`)
    .join('\n    ');
}

function socialSvg({ description, plateRows }) {
  const light = semantic.light;
  const parcels = [
    { y: 168, width: 320, height: 64, ticks: 7 },
    { y: 272, width: 400, height: 88, ticks: 9 },
    { y: 400, width: 260, height: 56, ticks: 6 },
  ];
  const plate = parcels
    .map(
      (parcel, index) => `
    <path d="${slabPath({ x: 880, y: parcel.y, width: parcel.width, height: parcel.height })}" fill="${light['diagram-ciphertext-fill']}"/>
    ${metadataTicks({ x: 884, y: parcel.y, count: parcel.ticks, fill: light['diagram-boundary'] })}
    <text x="880" y="${parcel.y + parcel.height + 26}" fill="${light.subtle}" font-family="${monoStack}" font-size="15">${plateRows[index]}</text>`,
    )
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="640" viewBox="0 0 1280 640" role="img" aria-labelledby="title desc">
  <title id="title">OpenE2EE Design</title>
  <desc id="desc">The OpenE2EE mark and wordmark beside a manifest plate: an outlined carrier holding three opaque parcels, each marked with brass metadata ticks.</desc>
  <rect width="1280" height="640" fill="${light.canvas}"/>
  <g>
    ${carrierBrackets({ x: 800, y: 104, width: 600, height: 432, thickness: 24, arm: 88, fill: light['diagram-carrier-stroke'] })}
    <path d="${slabPath({ x: 692, y: 424, width: 76, height: 132, shear: 12 })}" fill="${light['diagram-ciphertext-fill']}"/>
    ${metadataTicks({ x: 708, y: 424, count: 4, fill: light['diagram-boundary'] })}${plate}
  </g>
  <g transform="translate(88 88) scale(0.1875)">
${markMarkup(light.foreground, 'full', '    ')}
  </g>
  <text x="220" y="166" fill="${light.foreground}" font-family="${sansStack}" font-size="85">
    <tspan font-weight="500" letter-spacing="-0.85">Open</tspan><tspan font-weight="800" letter-spacing="-1.28">E2EE</tspan>
  </text>
  <rect x="88" y="240" width="616" height="1" fill="${light.border}"/>
  <text x="88" y="300" fill="${light.muted}" font-family="${sansStack}" font-size="28" font-weight="500">${description}</text>
  <text x="88" y="556" fill="${light.subtle}" font-family="${monoStack}" font-size="19">${packageJson.name} · ${packageJson.version}</text>
</svg>
`;
}

const generatedSoFar = await filesIn(generatedBrand);
const countIn = (prefix) =>
  generatedSoFar.filter((file) => file.startsWith(prefix)).length;

await mkdir(join(generatedBrand, 'social'), { recursive: true });
await writeText(
  join(generatedBrand, 'social', 'open-e2ee-design-og.svg'),
  socialSvg({
    description: 'Brand identity, design tokens, and theming.',
    plateRows: [
      `svg/ · ${countIn('svg/')} files`,
      `png/ · ${countIn('png/')} files`,
      `css/ · tokens · tailwind · fonts`,
    ],
  }),
);
execFileSync('rsvg-convert', [
  '--width',
  '1280',
  '--height',
  '640',
  '--output',
  join(generatedBrand, 'social', 'open-e2ee-design-og.png'),
  join(generatedBrand, 'social', 'open-e2ee-design-og.svg'),
]);

await cp(generatedBrand, assetDistribution, { recursive: true });

const assetDigest = await digestDirectory(generatedBrand);
const assetFiles = await filesIn(generatedBrand);
const manifest = {
  package: packageJson.name,
  version: packageJson.version,
  mark: geometry.mark,
  variants: {
    rule: geometry.rules.variantBySize,
    minimumSize: geometry.minimumSize,
    smallMaximumSize: geometry.smallMaximumSize,
    png: pngVariants,
  },
  sha256: assetDigest,
  files: assetFiles,
};
await writeText(
  join(generatedBrand, 'manifest.json'),
  JSON.stringify(manifest, null, 2),
);
await writeText(
  join(assetDistribution, 'manifest.json'),
  JSON.stringify(manifest, null, 2),
);

process.stdout.write(
  `Built ${packageJson.name} ${packageJson.version} with ${assetFiles.length} assets.\n`,
);
