import { execFileSync } from 'node:child_process';
import { cp, mkdir, rm } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  cssDeclarations,
  digestDirectory,
  filesIn,
  flatten,
  monoWidth,
  readJson,
  resolveReferences,
  textWidth,
  writeText,
} from './lib.mjs';
/*
 * The diagram grammar comes from the published package, not from private
 * copies here: the social card is drawn with the same functions a consumer
 * gets, so a change to the grammar cannot silently diverge from the assets
 * this repository ships.
 */
import {
  TICK_GAP,
  TICK_LENGTH,
  carrierBrackets,
  metadataTicks,
  slabPath,
} from '../packages/design/src/diagram.mjs';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const root = resolve(scriptDirectory, '..');
const generatedBrand = join(root, 'brand', 'generated');
const distribution = join(root, 'packages', 'design', 'dist');
const assetDistribution = join(distribution, 'assets');

const primitives = await readJson(join(root, 'tokens', 'primitives.json'));
const semanticSource = await readJson(join(root, 'tokens', 'semantic.json'));
const componentSource = await readJson(join(root, 'tokens', 'components.json'));
const brandSource = await readJson(join(root, 'tokens', 'brand.json'));
const geometry = await readJson(join(root, 'brand', 'source', 'geometry.json'));
const lockupSource = await readJson(join(root, 'brand', 'source', 'lockups.json'));
const typeMetrics = await readJson(
  join(root, 'brand', 'source', 'public-sans-metrics.json'),
);
const socialCardSource = await readJson(
  join(root, 'brand', 'source', 'social-cards.json'),
);
const packageJson = await readJson(join(root, 'package.json'));

const semantic = resolveReferences(semanticSource, primitives);
const components = resolveReferences(componentSource, primitives);
const brand = resolveReferences(brandSource, primitives);

/* Font stacks quote family names; SVG attributes are already double-quoted. */
const svgFont = (stack) => stack.replaceAll('"', "'");
const sansStack = svgFont(primitives.font.sans);
const monoStack = svgFont(primitives.font.mono);

await rm(generatedBrand, { recursive: true, force: true });
await rm(distribution, { recursive: true, force: true });
await mkdir(generatedBrand, { recursive: true });
await mkdir(distribution, { recursive: true });

function tokenCss() {
  const primitiveEntries = flatten(primitives);
  const componentEntries = flatten(components);
  return `/*
 * Generated by @open-e2ee/design. Do not edit directly.
 * Source: tokens/*.json
 */

:root {
  color-scheme: light;
${cssDeclarations(primitiveEntries)}

${cssDeclarations(flatten(semantic.light))}

${cssDeclarations(componentEntries)}
}

:root.dark {
  color-scheme: dark;
${cssDeclarations(flatten(semantic.dark))}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --oe-duration-fast: 0.01ms;
    --oe-duration-normal: 0.01ms;
    --oe-duration-slow: 0.01ms;
  }
}
`;
}

function tailwindCss() {
  const declarations = (entries) =>
    entries.map(([name, value]) => `  --${name}: ${value};`).join('\n');
  const colors = flatten(primitives.color).map(([name, value]) => [
    `color-oe-${name}`,
    value,
  ]);
  const radii = flatten(primitives.radius).map(([name, value]) => [
    `radius-brand-${name}`,
    value,
  ]);
  const semanticColors = Object.keys(semantic.light)
    .filter((key) => !key.startsWith('shadow-'))
    .map((key) => [`color-${key}`, `var(--oe-${key})`]);
  const semanticShadows = [
    ['shadow-brand-sm', 'var(--oe-shadow-sm)'],
    ['shadow-brand-md', 'var(--oe-shadow-md)'],
  ];

  return `/*
 * Generated Tailwind CSS v4 adapter. Import after "tailwindcss".
 */

@import "./tokens.css";

@custom-variant dark (&:where(.dark, .dark *));

@theme static {
${declarations(colors)}
  --font-brand-sans: ${primitives.font.sans};
  --font-brand-serif: ${primitives.font.serif};
  --font-brand-mono: ${primitives.font.mono};
${declarations(radii)}
}

@theme inline {
${declarations(semanticColors)}
${declarations(semanticShadows)}
}
`;
}

const fontsCss = `/*
 * Optional self-hosted OpenE2EE typefaces.
 * Imported from package dependencies; no third-party font request is made.
 *
 * Public Sans is the only family on the critical path. Newsreader (editorial
 * prose) and JetBrains Mono (code, identifiers, metadata) are worth preloading
 * per route rather than globally.
 */

@import "@fontsource-variable/public-sans";
@import "@fontsource-variable/newsreader";
@import "@fontsource-variable/jetbrains-mono";
`;

/*
 * The wordmark ships as live text, not as outlines: the weight contrast
 * between "Open" and "E2EE" is the whole concept, and a variable font renders
 * it at any size without shipping a second asset. See DESIGN.md for the four
 * craft corrections that a later outlined wordmark.svg should apply.
 */
const wordmarkCss = `/*
 * Generated by @open-e2ee/design. Do not edit directly.
 * Source: tokens/components.json
 *
 * Usage: <span class="oe-wordmark"><span>Open</span><span>E2EE</span></span>
 */

@import "./tokens.css";

.oe-wordmark {
  font-family: var(--oe-wordmark-font-family);
  font-style: normal;
  white-space: nowrap;
  font-synthesis-weight: none;
}

.oe-wordmark > :first-child {
  font-weight: var(--oe-wordmark-open-weight);
  letter-spacing: var(--oe-wordmark-open-tracking);
}

.oe-wordmark > :last-child {
  font-weight: var(--oe-wordmark-e2ee-weight);
  letter-spacing: var(--oe-wordmark-e2ee-tracking);
}

/*
 * Below 14px the weight contrast stops resolving and starts reading as a
 * rendering bug, so the wordmark reverts to one uniform weight.
 */
.oe-wordmark-small > :first-child,
.oe-wordmark-small > :last-child {
  font-weight: var(--oe-wordmark-small-weight);
  letter-spacing: var(--oe-wordmark-small-tracking);
}
`;

const themeModule = `const STORAGE_KEY = 'oe-theme';
const THEMES = new Set(['light', 'dark', 'system']);

function systemPrefersDark() {
  return typeof matchMedia === 'function' &&
    matchMedia('(prefers-color-scheme: dark)').matches;
}

export function resolveTheme(preference = 'system') {
  return preference === 'dark' ||
    (preference === 'system' && systemPrefersDark())
    ? 'dark'
    : 'light';
}

export function applyTheme(preference = 'system', root = document.documentElement) {
  const resolved = resolveTheme(preference);
  root.classList.toggle('dark', resolved === 'dark');
  root.style.colorScheme = resolved;
  return resolved;
}

export function getStoredTheme(storage = localStorage) {
  const value = storage.getItem(STORAGE_KEY) ?? 'system';
  return THEMES.has(value) ? value : 'system';
}

export function applyStoredTheme(options = {}) {
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  return applyTheme(getStoredTheme(storage), root);
}

export function setTheme(preference, options = {}) {
  if (!THEMES.has(preference)) {
    throw new TypeError('Theme must be "light", "dark", or "system".');
  }
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  storage.setItem(STORAGE_KEY, preference);
  return applyTheme(preference, root);
}

export function watchSystemTheme(options = {}) {
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  const query = matchMedia('(prefers-color-scheme: dark)');
  const listener = () => {
    if (getStoredTheme(storage) === 'system') applyTheme('system', root);
  };
  query.addEventListener('change', listener);
  return () => query.removeEventListener('change', listener);
}

export { STORAGE_KEY, THEMES };
`;

await writeText(join(distribution, 'css', 'tokens.css'), tokenCss());
await writeText(join(distribution, 'css', 'tailwind.css'), tailwindCss());
await writeText(join(distribution, 'css', 'fonts.css'), fontsCss);
await writeText(join(distribution, 'css', 'wordmark.css'), wordmarkCss);
await writeText(join(distribution, 'theme.mjs'), themeModule);
/*
 * `diagram` and `taglines` are authored by hand under packages/design/src and
 * copied verbatim; only the CSS and the theme module are generated from tokens.
 * Copying rather than generating keeps them readable, reviewable, and directly
 * importable by scripts/ — one implementation, not a template of one.
 */
const copiedModules = ['diagram', 'taglines'];
for (const name of copiedModules) {
  for (const extension of ['mjs', 'd.ts']) {
    await cp(
      join(root, 'packages', 'design', 'src', `${name}.${extension}`),
      join(distribution, `${name}.${extension}`),
    );
  }
}

await writeText(
  join(distribution, 'index.mjs'),
  `export * from './theme.mjs';
export * from './diagram.mjs';
export * from './taglines.mjs';
`,
);
await writeText(
  join(distribution, 'theme.d.ts'),
  `export type ThemePreference = 'light' | 'dark' | 'system';
export type ResolvedTheme = 'light' | 'dark';
export interface ThemeOptions {
  storage?: Storage;
  root?: HTMLElement;
}
export declare function resolveTheme(preference?: ThemePreference): ResolvedTheme;
export declare function applyTheme(
  preference?: ThemePreference,
  root?: HTMLElement,
): ResolvedTheme;
export declare function getStoredTheme(storage?: Storage): ThemePreference;
export declare function applyStoredTheme(options?: ThemeOptions): ResolvedTheme;
export declare function setTheme(
  preference: ThemePreference,
  options?: ThemeOptions,
): ResolvedTheme;
export declare function watchSystemTheme(options?: ThemeOptions): () => void;
export declare const STORAGE_KEY: 'oe-theme';
export declare const THEMES: ReadonlySet<ThemePreference>;
`,
);
await writeText(
  join(distribution, 'index.d.ts'),
  `export * from './theme.js';
export * from './diagram.js';
export * from './taglines.js';
`,
);
await writeText(
  join(distribution, 'tokens.json'),
  JSON.stringify({ primitives, semantic, components, brand, geometry }, null, 2),
);

/*
 * The Carrier mark.
 *
 * Two hollow carrier brackets hold one solid payload that touches neither of
 * them. Everything is a single fill color: no strokes, no radii, no gradients,
 * no second tone. The payload is square at every size; the two variants differ
 * so the silhouette survives at favicon sizes.
 */

const markSizes = [16, 24, 32, 48, 64, 128, 256, 512, 1024];

function variantForSize(size) {
  if (size < geometry.minimumSize) {
    throw new Error(`The mark is not reproduced below ${geometry.minimumSize} px.`);
  }
  return size <= geometry.smallMaximumSize ? 'optical' : 'full';
}

function markPaths(variant) {
  const { carrierLeftPath, carrierRightPath, payloadPath } = geometry[variant];
  return [carrierLeftPath, carrierRightPath, payloadPath];
}

const markDescription = {
  full:
    'Two open carrier brackets holding a solid square payload. The payload ' +
    'touches neither bracket.',
  optical:
    'Two open carrier brackets holding a solid square payload. Small-size ' +
    'optical variant, drawn with thicker stems for favicon scale.',
};

function markMarkup(fill, variant, indent = '  ') {
  return markPaths(variant)
    .map((path) => `${indent}<path d="${path}" fill="${fill}"/>`)
    .join('\n');
}

const forcedColors = `    @media (forced-colors: active) {
      path { fill: CanvasText; }
    }`;

function standaloneSvg({ mode, fill, variant, background }) {
  const sizeLabel = variant === 'optical' ? ' small-size' : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${geometry.viewBox}" role="img" aria-labelledby="title desc">
  <title id="title">OpenE2EE${sizeLabel} mark — ${mode}</title>
  <desc id="desc">${markDescription[variant]}</desc>
  <metadata>Mark: carrier; variant: ${variant}; mode: ${mode}; intended background: ${background}; generated by @open-e2ee/design ${packageJson.version}.</metadata>
  <style>
${forcedColors}
  </style>
${markMarkup(fill, variant)}
</svg>
`;
}

function adaptiveSvg(variant, { title, width = 512 } = {}) {
  const sizeLabel = variant === 'optical' ? ' small-size' : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${width}" viewBox="${geometry.viewBox}" role="img" aria-labelledby="title desc">
  <title id="title">${title ?? `Adaptive OpenE2EE${sizeLabel} mark`}</title>
  <desc id="desc">${markDescription[variant]} The fill follows the active color scheme.</desc>
  <style>
    :root { --oe-mark: ${brand.modes.light.mark}; }
    @media (prefers-color-scheme: dark) {
      :root { --oe-mark: ${brand.modes.dark.mark}; }
    }
${forcedColors}
  </style>
${markMarkup('var(--oe-mark)', variant)}
</svg>
`;
}

const svgDirectory = join(generatedBrand, 'svg');
const pngDirectory = join(generatedBrand, 'png');
await mkdir(svgDirectory, { recursive: true });
await mkdir(pngDirectory, { recursive: true });

const variantSvgPath = {};
for (const variant of ['full', 'optical']) {
  const suffix = variant === 'optical' ? '-small' : '';
  for (const [mode, colors] of Object.entries(brand.modes)) {
    const path = join(svgDirectory, `open-e2ee-mark-${mode}${suffix}.svg`);
    await writeText(
      path,
      standaloneSvg({
        mode: `${mode} mode`,
        fill: colors.mark,
        variant,
        background: colors.background,
      }),
    );
    variantSvgPath[`${mode}-${variant}`] = path;
  }

  await writeText(
    join(svgDirectory, `open-e2ee-mark-mono${suffix}.svg`),
    standaloneSvg({
      mode: 'monochrome',
      fill: 'currentColor',
      variant,
      background: 'any',
    }),
  );
  await writeText(
    join(generatedBrand, `open-e2ee-mark-adaptive${suffix}.svg`),
    adaptiveSvg(variant),
  );
}

await writeText(
  join(generatedBrand, 'open-e2ee-favicon.svg'),
  adaptiveSvg('optical', { title: 'OpenE2EE', width: 32 }),
);

const pngVariants = {};
for (const size of markSizes) {
  const variant = variantForSize(size);
  pngVariants[size] = variant;
  const outputDirectory = join(pngDirectory, String(size));
  await mkdir(outputDirectory, { recursive: true });
  for (const mode of Object.keys(brand.modes)) {
    execFileSync('rsvg-convert', [
      '--width',
      String(size),
      '--height',
      String(size),
      '--output',
      join(outputDirectory, `open-e2ee-mark-${mode}.png`),
      variantSvgPath[`${mode}-${variant}`],
    ]);
  }
}

/*
 * Presentation sheet: both modes, and the size rule drawn rather than stated.
 */
function sheetSvg() {
  const width = 1240;
  const height = 680;
  const sampleSizes = [16, 24, 32, 64];
  const cards = Object.entries(brand.modes).map(([mode, colors], index) => {
    const x = 40 + index * 600;
    let cursor = 48;
    const samples = sampleSizes.map((size) => {
      const variant = variantForSize(size);
      const scale = size / 512;
      const markup = `
      <g transform="translate(${cursor} ${64 - size}) scale(${scale})">
${markMarkup(colors.mark, variant, '        ')}
      </g>
      <text x="${cursor}" y="88" fill="${colors.mark}" font-family="${monoStack}" font-size="13" opacity="0.72">${size}px ${variant}</text>`;
      cursor += Math.max(size, 74) + 34;
      return markup;
    });
    return `
  <g transform="translate(${x} 40)">
    <rect width="560" height="600" fill="${colors.background}"/>
    <g transform="translate(120 40) scale(0.625)">
${markMarkup(colors.mark, 'full', '      ')}
    </g>
    <g transform="translate(40 424)">${samples.join('')}
    </g>
    <text x="40" y="558" fill="${colors.label}" font-family="${monoStack}" font-size="20" font-weight="600" letter-spacing="1.4">${mode.toUpperCase()} MODE</text>
  </g>`;
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc">
  <title id="title">The OpenE2EE mark in light and dark modes</title>
  <desc id="desc">The full mark above the size rule: the optical variant from 16 to 31 px, the full mark from 32 px.</desc>
  <rect width="${width}" height="${height}" fill="${brand.sheet.background}"/>${cards.join('')}
</svg>
`;
}

await writeText(join(generatedBrand, 'open-e2ee-mark-sheet.svg'), sheetSvg());
execFileSync('rsvg-convert', [
  '--width',
  '1240',
  '--height',
  '680',
  '--output',
  join(generatedBrand, 'open-e2ee-mark-sheet.png'),
  join(generatedBrand, 'open-e2ee-mark-sheet.svg'),
]);

const escapeXml = (value) =>
  String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');

const round2 = (value) => Number(value.toFixed(2));
const capRatio = typeMetrics.capHeight / typeMetrics.unitsPerEm;
const descenderRatio = typeMetrics.descender / typeMetrics.unitsPerEm;

const measure = (text, options) =>
  options.mono === true
    ? monoWidth(text, options.size)
    : textWidth(typeMetrics, text, options);

/*
 * Generated SVG has no layout engine behind it, so every string this build
 * draws is measured against the box drawn for it. A description that would run
 * under the plate fails the build instead of shipping.
 */
function fitText(text, options, limit, context) {
  const width = measure(text, options);
  if (width > limit) {
    throw new Error(
      `${context}: ${JSON.stringify(text)} measures ${width.toFixed(1)} px, ${(width - limit).toFixed(1)} px past its ${limit} px box.`,
    );
  }
  return width;
}

/*
 * Social preview (1280x640): canvas, mark, wordmark, a description block, and a
 * manifest plate on the right. The plate is an object store drawn in the
 * diagram grammar — an outlined carrier holding opaque parcels, brass metadata
 * ticks on every one — annotated with rows that are true of the repository the
 * card describes.
 *
 * The carrier is drawn whole: both brackets stand on the canvas, because the
 * form is a pair and one bracket is a different mark. The plate column is
 * therefore bounded by the right bracket's inner face, and the left column is
 * bounded by the left bracket.
 */
const CARD = {
  width: 1280,
  height: 640,
  /* Carrier: 800..1240, so the right bracket sits 40 px inside the canvas. */
  carrier: { x: 800, y: 104, width: 440, height: 432, thickness: 24, arm: 88 },
  parcelX: 856,
  /* Interior clearance to the bracket stems is the trust boundary; it holds. */
  parcelMaxWidth: 330,
  /* The left column ends where the carrier begins, less a gutter. */
  columnX: 88,
  columnWidth: 692,
  parcels: [
    { y: 150, width: 264, height: 64, ticks: 7 },
    { y: 268, width: 330, height: 88, ticks: 9 },
    { y: 412, width: 215, height: 56, ticks: 6 },
  ],
  /*
   * An in-transit envelope, sheared, clear of the carrier's left bracket. It
   * sits low enough that its metadata ticks stay below the description block
   * and its foot lands on the footer baseline.
   */
  transit: { x: 692, y: 440, width: 76, height: 116, shear: 12, ticks: 4 },
  /* Labels stop a gutter short of the right bracket's inner face. */
  labelGutter: 16,
  labelBaselineOffset: 24,
  labelSize: 15,
  wordmarkBaseline: 166,
  wordmarkSize: 85,
  descriptionSize: 28,
  descriptionLeading: 40,
  footerBaseline: 556,
};

function socialSvg({ title, product, description, plateRows, footer }) {
  const light = semantic.light;
  const labelLimit =
    CARD.carrier.x +
    CARD.carrier.width -
    CARD.carrier.thickness -
    CARD.labelGutter -
    CARD.parcelX;

  const plate = CARD.parcels
    .map((parcel, index) => {
      const row = plateRows[index];
      fitText(
        row,
        { size: CARD.labelSize, mono: true },
        labelLimit,
        `${title} plate row ${index + 1}`,
      );
      return `
    <path d="${slabPath({ x: CARD.parcelX, y: parcel.y, width: parcel.width, height: parcel.height })}" fill="${light['diagram-ciphertext-fill']}"/>
    ${metadataTicks({ x: CARD.parcelX + 4, y: parcel.y, count: parcel.ticks, fill: light['diagram-boundary'] })}
    <text x="${CARD.parcelX}" y="${parcel.y + parcel.height + CARD.labelBaselineOffset}" fill="${light.subtle}" font-family="${monoStack}" font-size="${CARD.labelSize}">${escapeXml(row)}</text>`;
    })
    .join('');

  /*
   * A card for a product names the product, on a second line built to the same
   * proportions as the product lockup. Cards for the org set the wordmark
   * alone, and everything below simply moves up.
   */
  const cardCap = CARD.wordmarkSize * capRatio;
  const productSizeOnCard =
    (cardCap * lockupSource.proportions.productCapHeight) / capRatio;
  const productBaseline =
    CARD.wordmarkBaseline + cardCap * lockupSource.proportions.productBaseline;
  const ruleY = product ? productBaseline + 40 : 240;
  const descriptionTop = ruleY + 60;

  if (product) {
    fitText(
      product,
      { size: productSizeOnCard, weight: lockupSource.productWeight },
      CARD.columnWidth,
      `${title} product line`,
    );
  }
  const productLine = product
    ? `
  <text x="${CARD.columnX}" y="${round2(productBaseline)}" fill="${light.muted}" font-family="${sansStack}" font-size="${round2(productSizeOnCard)}" font-weight="${lockupSource.productWeight}">${escapeXml(product)}</text>`
    : '';

  const descriptionLines = description
    .map((line, index) => {
      fitText(
        line,
        { size: CARD.descriptionSize },
        CARD.columnWidth,
        `${title} description line ${index + 1}`,
      );
      return `
  <text x="${CARD.columnX}" y="${descriptionTop + index * CARD.descriptionLeading}" fill="${light.muted}" font-family="${sansStack}" font-size="${CARD.descriptionSize}" font-weight="500">${escapeXml(line)}</text>`;
    })
    .join('');

  const descriptionBottom =
    descriptionTop +
    (description.length - 1) * CARD.descriptionLeading +
    descenderRatio * CARD.descriptionSize;
  const transitTickTop = CARD.transit.y - TICK_LENGTH - TICK_GAP;
  if (descriptionBottom > transitTickTop) {
    throw new Error(
      `${title}: the description block reaches ${descriptionBottom.toFixed(1)} px, into the in-transit envelope's metadata ticks at ${transitTickTop} px.`,
    );
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${CARD.width}" height="${CARD.height}" viewBox="0 0 ${CARD.width} ${CARD.height}" role="img" aria-labelledby="title desc">
  <title id="title">${escapeXml(title)}</title>
  <desc id="desc">The OpenE2EE mark and wordmark beside a manifest plate: two open carrier brackets holding three opaque parcels, each marked with brass metadata ticks, with a fourth parcel in transit outside the carrier.</desc>
  <rect width="${CARD.width}" height="${CARD.height}" fill="${light.canvas}"/>
  <g>
    ${carrierBrackets({ ...CARD.carrier, fill: light['diagram-carrier-stroke'] }).replaceAll('\n', '\n    ')}
    <path d="${slabPath(CARD.transit)}" fill="${light['diagram-ciphertext-fill']}"/>
    ${metadataTicks({ x: CARD.transit.x + 16, y: CARD.transit.y, count: CARD.transit.ticks, fill: light['diagram-boundary'] })}${plate}
  </g>
  <g transform="translate(88 88) scale(0.1875)">
${markMarkup(light.foreground, 'full', '    ')}
  </g>
  <text x="220" y="${CARD.wordmarkBaseline}" fill="${light.foreground}" font-family="${sansStack}" font-size="${CARD.wordmarkSize}">
    <tspan font-weight="500" letter-spacing="-0.85">Open</tspan><tspan font-weight="800" letter-spacing="-1.28">E2EE</tspan>
  </text>${productLine}
  <rect x="${CARD.columnX}" y="${round2(ruleY)}" width="${CARD.columnWidth}" height="1" fill="${light.border}"/>${descriptionLines}
  <text x="${CARD.columnX}" y="${CARD.footerBaseline}" fill="${light.subtle}" font-family="${monoStack}" font-size="19">${escapeXml(footer)}</text>
</svg>
`;
}

const generatedSoFar = await filesIn(generatedBrand);
const countIn = (prefix) =>
  generatedSoFar.filter((file) => file.startsWith(prefix)).length;

/*
 * Only these substitutions exist, and they are all facts about this repository.
 * A card describing another repository states that repository's facts as
 * literal copy, reviewed as copy — the build has no way to verify a claim about
 * a repository it cannot see, so it must not look like it did.
 */
const cardSubstitutions = {
  '{version}': packageJson.version,
  '{package}': packageJson.name,
  '{svgFiles}': String(countIn('svg/')),
  '{pngFiles}': String(countIn('png/')),
};

const fillCard = (value) =>
  Object.entries(cardSubstitutions).reduce(
    (text, [token, replacement]) => text.replaceAll(token, replacement),
    value,
  );

const socialDirectory = join(generatedBrand, 'social');
await mkdir(socialDirectory, { recursive: true });

const socialCards = [];
for (const card of socialCardSource.cards) {
  const svgPath = join(socialDirectory, `${card.slug}.svg`);
  const pngPath = join(socialDirectory, `${card.slug}.png`);
  await writeText(
    svgPath,
    socialSvg({
      title: card.title,
      product: card.product,
      description: card.description.map(fillCard),
      plateRows: card.plateRows.map(fillCard),
      footer: fillCard(card.footer),
    }),
  );
  execFileSync('rsvg-convert', [
    '--width',
    String(CARD.width),
    '--height',
    String(CARD.height),
    '--output',
    pngPath,
    svgPath,
  ]);
  socialCards.push({
    slug: card.slug,
    subject: card.subject,
    title: card.title,
    svg: `social/${card.slug}.svg`,
    png: `social/${card.slug}.png`,
  });
}

/*
 * Lockups.
 *
 * DESIGN.md's lockup table is a set of ratios, not a set of files; until now
 * every consumer re-derived them by hand in CSS and got a different answer.
 * These are the ratios executed once, against real font metrics.
 *
 * SVG only: rsvg-convert cannot load a webfont, so a rasterized lockup would
 * silently set the wordmark in whatever the host machine had lying around.
 */
const lockupDirectory = join(generatedBrand, 'lockup');
await mkdir(lockupDirectory, { recursive: true });

const symbol = lockupSource.symbolSize;
const lockupPad = symbol * geometry.clearSpaceRatio;
const wordmarkCap = symbol * lockupSource.proportions.wordmarkCapHeight;
const wordmarkSize = wordmarkCap / capRatio;
const symbolGap = symbol * lockupSource.proportions.symbolGap;
const stackedGap = symbol * lockupSource.proportions.stackedGap;
const productCap = wordmarkCap * lockupSource.proportions.productCapHeight;
const productSize = productCap / capRatio;
const productDrop = wordmarkCap * lockupSource.proportions.productBaseline;
const wordmarkWidth =
  textWidth(typeMetrics, lockupSource.wordmark.open, {
    size: wordmarkSize,
    weight: lockupSource.wordmark.openWeight,
    tracking: lockupSource.wordmark.openTracking,
  }) +
  textWidth(typeMetrics, lockupSource.wordmark.e2ee, {
    size: wordmarkSize,
    weight: lockupSource.wordmark.e2eeWeight,
    tracking: lockupSource.wordmark.e2eeTracking,
  });
const productWidth = textWidth(typeMetrics, lockupSource.product, {
  size: productSize,
  weight: lockupSource.productWeight,
});

function wordmarkText({ x, y, fill, size }) {
  const { open, e2ee, openWeight, e2eeWeight, openTracking, e2eeTracking } =
    lockupSource.wordmark;
  return `<text x="${round2(x)}" y="${round2(y)}" fill="${fill}" font-family="${sansStack}" font-size="${round2(size)}">
    <tspan font-weight="${openWeight}" letter-spacing="${round2(openTracking * size)}">${open}</tspan><tspan font-weight="${e2eeWeight}" letter-spacing="${round2(e2eeTracking * size)}">${e2ee}</tspan>
  </text>`;
}

function lockupSvg({ name, mode, colors, width, height, description, body }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${round2(width)}" height="${round2(height)}" viewBox="0 0 ${round2(width)} ${round2(height)}" role="img" aria-labelledby="title desc">
  <title id="title">OpenE2EE ${name} lockup — ${mode}</title>
  <desc id="desc">${description}</desc>
  <metadata>Lockup: ${name}; mode: ${mode}; symbol height ${symbol}; wordmark cap height ${round2(wordmarkCap)}; generated by @open-e2ee/design ${packageJson.version}. Set in Public Sans; the wordmark is live text and needs the family available.</metadata>
${body(colors)}
</svg>
`;
}

/* Symbol height S is fixed, so every lockup places the mark at the same scale. */
const symbolAt = (x, y, fill) =>
  `  <g transform="translate(${round2(x)} ${round2(y)}) scale(${round2(symbol / 512)})">
${markMarkup(fill, variantForSize(symbol), '    ')}
  </g>`;

const lockupModes = {
  ...brand.modes,
  mono: { mark: 'currentColor', label: 'currentColor', product: 'currentColor' },
};

const lockupGeometry = {
  symbol: {
    width: symbol + lockupPad * 2,
    height: symbol + lockupPad * 2,
    description:
      'The OpenE2EE symbol alone, with one bracket stem of clear space on every side.',
    body: (colors) => symbolAt(lockupPad, lockupPad, colors.mark),
  },
  horizontal: {
    width: lockupPad * 2 + symbol + symbolGap + wordmarkWidth,
    height: symbol + lockupPad * 2,
    description:
      'The OpenE2EE symbol beside the wordmark, centered on each other vertically.',
    body: (colors) =>
      `${symbolAt(lockupPad, lockupPad, colors.mark)}
  ${wordmarkText({
    x: lockupPad + symbol + symbolGap,
    /* Centered on the symbol, never baseline-aligned. */
    y: lockupPad + symbol / 2 + wordmarkCap / 2,
    fill: colors.label,
    size: wordmarkSize,
  })}`,
  },
  stacked: {
    width: Math.max(symbol, wordmarkWidth) + lockupPad * 2,
    height:
      lockupPad * 2 +
      symbol +
      stackedGap +
      wordmarkCap +
      descenderRatio * wordmarkSize,
    description: 'The OpenE2EE symbol above the wordmark, centered on each other.',
    body: (colors) => {
      const width = Math.max(symbol, wordmarkWidth) + lockupPad * 2;
      return `${symbolAt((width - symbol) / 2, lockupPad, colors.mark)}
  ${wordmarkText({
    x: (width - wordmarkWidth) / 2,
    y: lockupPad + symbol + stackedGap + wordmarkCap,
    fill: colors.label,
    size: wordmarkSize,
  })}`;
    },
  },
  product: {
    width: Math.max(
      lockupPad * 2 + symbol + symbolGap + wordmarkWidth,
      lockupPad * 2 + productWidth,
    ),
    height:
      lockupPad * 2 +
      symbol / 2 +
      wordmarkCap / 2 +
      productDrop +
      descenderRatio * productSize,
    description:
      'The horizontal OpenE2EE lockup with the product name on a second line, flush with the left edge of the symbol.',
    body: (colors) => {
      const wordmarkBaseline = lockupPad + symbol / 2 + wordmarkCap / 2;
      return `${symbolAt(lockupPad, lockupPad, colors.mark)}
  ${wordmarkText({
    x: lockupPad + symbol + symbolGap,
    y: wordmarkBaseline,
    fill: colors.label,
    size: wordmarkSize,
  })}
  <text x="${round2(lockupPad)}" y="${round2(wordmarkBaseline + productDrop)}" fill="${colors.product}" font-family="${sansStack}" font-size="${round2(productSize)}" font-weight="${lockupSource.productWeight}">${escapeXml(lockupSource.product)}</text>`;
    },
  },
};

const lockups = [];
for (const [name, definition] of Object.entries(lockupGeometry)) {
  for (const [mode, colors] of Object.entries(lockupModes)) {
    const file = `open-e2ee-lockup-${name}-${mode}.svg`;
    await writeText(
      join(lockupDirectory, file),
      lockupSvg({ name, mode, colors, ...definition }),
    );
    lockups.push({
      lockup: name,
      mode,
      svg: `lockup/${file}`,
      width: round2(definition.width),
      height: round2(definition.height),
    });
  }
}

await cp(generatedBrand, assetDistribution, { recursive: true });

const assetDigest = await digestDirectory(generatedBrand);
const assetFiles = await filesIn(generatedBrand);
const manifest = {
  package: packageJson.name,
  version: packageJson.version,
  mark: geometry.mark,
  variants: {
    rule: geometry.rules.variantBySize,
    minimumSize: geometry.minimumSize,
    smallMaximumSize: geometry.smallMaximumSize,
    png: pngVariants,
  },
  lockups: {
    rule: 'Lockup proportions are derived from the symbol height S and the Public Sans cap height; see DESIGN.md.',
    symbolSize: symbol,
    wordmarkCapHeight: round2(wordmarkCap),
    wordmarkFontSize: round2(wordmarkSize),
    symbolGap: round2(symbolGap),
    stackedGap: round2(stackedGap),
    productFontSize: round2(productSize),
    productBaselineDrop: round2(productDrop),
    note: 'SVG only, and the wordmark is live text: a lockup needs Public Sans available to render as drawn.',
    assets: lockups,
  },
  social: {
    rule: 'One card per repository, generated from brand/source/social-cards.json. Plate rows are copy about the repository named in `subject`.',
    size: { width: CARD.width, height: CARD.height },
    assets: socialCards,
  },
  sha256: assetDigest,
  files: assetFiles,
};
await writeText(
  join(generatedBrand, 'manifest.json'),
  JSON.stringify(manifest, null, 2),
);
await writeText(
  join(assetDistribution, 'manifest.json'),
  JSON.stringify(manifest, null, 2),
);

process.stdout.write(
  `Built ${packageJson.name} ${packageJson.version} with ${assetFiles.length} assets.\n`,
);
