import { execFileSync } from 'node:child_process';
import { cp, mkdir, rm } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  cssDeclarations,
  digestDirectory,
  filesIn,
  flatten,
  readJson,
  resolveReferences,
  writeText,
} from './lib.mjs';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const root = resolve(scriptDirectory, '..');
const generatedBrand = join(root, 'brand', 'generated');
const distribution = join(root, 'packages', 'design', 'dist');
const assetDistribution = join(distribution, 'assets');

const primitives = await readJson(join(root, 'tokens', 'primitives.json'));
const semanticSource = await readJson(join(root, 'tokens', 'semantic.json'));
const componentSource = await readJson(join(root, 'tokens', 'components.json'));
const brandSource = await readJson(join(root, 'tokens', 'brand.json'));
const geometry = await readJson(join(root, 'brand', 'source', 'geometry.json'));
const packageJson = await readJson(join(root, 'package.json'));

const semantic = resolveReferences(semanticSource, primitives);
const components = resolveReferences(componentSource, primitives);
const brand = resolveReferences(brandSource, primitives);

await rm(generatedBrand, { recursive: true, force: true });
await rm(distribution, { recursive: true, force: true });
await mkdir(generatedBrand, { recursive: true });
await mkdir(distribution, { recursive: true });

function tokenCss() {
  const primitiveEntries = flatten(primitives);
  const componentEntries = flatten(components);
  return `/*
 * Generated by @open-e2ee/design. Do not edit directly.
 * Source: tokens/*.json
 */

:root {
  color-scheme: light;
${cssDeclarations(primitiveEntries)}

${cssDeclarations(flatten(semantic.light))}

${cssDeclarations(componentEntries)}
}

:root.dark {
  color-scheme: dark;
${cssDeclarations(flatten(semantic.dark))}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --oe-duration-fast: 0.01ms;
    --oe-duration-normal: 0.01ms;
    --oe-duration-slow: 0.01ms;
  }
}
`;
}

function tailwindCss() {
  const declarations = (entries) =>
    entries.map(([name, value]) => `  --${name}: ${value};`).join('\n');
  const colors = flatten(primitives.color).map(([name, value]) => [
    `color-oe-${name}`,
    value,
  ]);
  const radii = flatten(primitives.radius).map(([name, value]) => [
    `radius-brand-${name}`,
    value,
  ]);
  const semanticColors = Object.keys(semantic.light)
    .filter((key) => !key.startsWith('shadow-'))
    .map((key) => [`color-${key}`, `var(--oe-${key})`]);
  const semanticShadows = [
    ['shadow-brand-sm', 'var(--oe-shadow-sm)'],
    ['shadow-brand-md', 'var(--oe-shadow-md)'],
  ];

  return `/*
 * Generated Tailwind CSS v4 adapter. Import after "tailwindcss".
 */

@import "./tokens.css";

@custom-variant dark (&:where(.dark, .dark *));

@theme static {
${declarations(colors)}
  --font-brand-sans: ${primitives.font.sans};
  --font-brand-mono: ${primitives.font.mono};
${declarations(radii)}
}

@theme inline {
${declarations(semanticColors)}
${declarations(semanticShadows)}
}
`;
}

const fontsCss = `/*
 * Optional self-hosted OpenE2EE typefaces.
 * Imported from package dependencies; no third-party font request is made.
 */

@import "@fontsource-variable/inter";
@import "@fontsource-variable/jetbrains-mono";
`;

const themeModule = `const STORAGE_KEY = 'oe-theme';
const THEMES = new Set(['light', 'dark', 'system']);

function systemPrefersDark() {
  return typeof matchMedia === 'function' &&
    matchMedia('(prefers-color-scheme: dark)').matches;
}

export function resolveTheme(preference = 'system') {
  return preference === 'dark' ||
    (preference === 'system' && systemPrefersDark())
    ? 'dark'
    : 'light';
}

export function applyTheme(preference = 'system', root = document.documentElement) {
  const resolved = resolveTheme(preference);
  root.classList.toggle('dark', resolved === 'dark');
  root.style.colorScheme = resolved;
  return resolved;
}

export function getStoredTheme(storage = localStorage) {
  const value = storage.getItem(STORAGE_KEY) ?? 'system';
  return THEMES.has(value) ? value : 'system';
}

export function applyStoredTheme(options = {}) {
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  return applyTheme(getStoredTheme(storage), root);
}

export function setTheme(preference, options = {}) {
  if (!THEMES.has(preference)) {
    throw new TypeError('Theme must be "light", "dark", or "system".');
  }
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  storage.setItem(STORAGE_KEY, preference);
  return applyTheme(preference, root);
}

export function watchSystemTheme(options = {}) {
  const storage = options.storage ?? localStorage;
  const root = options.root ?? document.documentElement;
  const query = matchMedia('(prefers-color-scheme: dark)');
  const listener = () => {
    if (getStoredTheme(storage) === 'system') applyTheme('system', root);
  };
  query.addEventListener('change', listener);
  return () => query.removeEventListener('change', listener);
}

export { STORAGE_KEY, THEMES };
`;

await writeText(join(distribution, 'css', 'tokens.css'), tokenCss());
await writeText(join(distribution, 'css', 'tailwind.css'), tailwindCss());
await writeText(join(distribution, 'css', 'fonts.css'), fontsCss);
await writeText(join(distribution, 'theme.mjs'), themeModule);
await writeText(
  join(distribution, 'index.mjs'),
  `export * from './theme.mjs';\n`,
);
await writeText(
  join(distribution, 'theme.d.ts'),
  `export type ThemePreference = 'light' | 'dark' | 'system';
export type ResolvedTheme = 'light' | 'dark';
export interface ThemeOptions {
  storage?: Storage;
  root?: HTMLElement;
}
export declare function resolveTheme(preference?: ThemePreference): ResolvedTheme;
export declare function applyTheme(
  preference?: ThemePreference,
  root?: HTMLElement,
): ResolvedTheme;
export declare function getStoredTheme(storage?: Storage): ThemePreference;
export declare function applyStoredTheme(options?: ThemeOptions): ResolvedTheme;
export declare function setTheme(
  preference: ThemePreference,
  options?: ThemeOptions,
): ResolvedTheme;
export declare function watchSystemTheme(options?: ThemeOptions): () => void;
export declare const STORAGE_KEY: 'oe-theme';
export declare const THEMES: ReadonlySet<ThemePreference>;
`,
);
await writeText(
  join(distribution, 'index.d.ts'),
  `export * from './theme.js';\n`,
);
await writeText(
  join(distribution, 'tokens.json'),
  JSON.stringify({ primitives, semantic, components, brand }, null, 2),
);

function logoMarkup(colors, { small = false, idSuffix = '' } = {}) {
  const rightHalfId = `shield-right-half${idSuffix}`;
  return `
  <defs>
    <clipPath id="${rightHalfId}">
      <rect x="256" width="256" height="512"/>
    </clipPath>
  </defs>
  <g>
    <path d="${geometry.shieldPath}" fill="${colors['shield-left']}"/>
    <path d="${geometry.shieldPath}" fill="${colors['shield-right']}" clip-path="url(#${rightHalfId})"/>
    <path d="${geometry.shieldPath}" fill="none" stroke="${small ? colors.accent : colors.outline}" stroke-width="${small ? 10 : 14}" stroke-linejoin="round"/>
    ${small ? '' : `<path d="${geometry.shieldPath}" fill="none" stroke="${colors.accent}" stroke-width="4" stroke-linejoin="round"/>`}
    <path d="${geometry.oGlyphPath}" fill="${colors.ink}" fill-rule="evenodd"/>
    <path d="${geometry.eGlyphPath}" fill="${colors.ink}"/>
  </g>`;
}

function standaloneSvg(mode, colors, { small = false } = {}) {
  const sizeLabel = small ? ' small-size' : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${geometry.viewBox}" role="img" aria-labelledby="title desc">
  <title id="title">OpenE2EE${sizeLabel} shield — ${mode} mode</title>
  <desc id="desc">A split-color shield containing geometric O and E letterforms.</desc>
  <metadata>Mode: ${mode}; small-size: ${small}; intended background: ${colors.background}; generated by @open-e2ee/design ${packageJson.version}.</metadata>${logoMarkup(colors, { small })}
</svg>
`;
}

function adaptiveSvg({ small = false } = {}) {
  const light = brand.light;
  const dark = brand.dark;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="${geometry.viewBox}" role="img" aria-labelledby="title desc">
  <title id="title">Adaptive OpenE2EE${small ? ' small-size' : ''} shield</title>
  <desc id="desc">A split-color shield containing geometric O and E letterforms. Colors adapt to the active color scheme.</desc>
  <style>
    :root { --shield-left: ${light['shield-left']}; --shield-right: ${light['shield-right']}; --outline: ${light.outline}; --accent: ${light.accent}; --ink: ${light.ink}; }
    @media (prefers-color-scheme: dark) {
      :root { --shield-left: ${dark['shield-left']}; --shield-right: ${dark['shield-right']}; --outline: ${dark.outline}; --accent: ${dark.accent}; --ink: ${dark.ink}; }
    }
  </style>
  ${logoMarkup({
    'shield-left': 'var(--shield-left)',
    'shield-right': 'var(--shield-right)',
    outline: 'var(--outline)',
    accent: 'var(--accent)',
    ink: 'var(--ink)',
  }, { small, idSuffix: '-adaptive' })}
</svg>
`;
}

function modeSheetSvg() {
  const width = 1240;
  const height = 680;
  const cards = Object.entries(brand).map(([mode, colors], index) => {
    const x = 40 + index * 600;
    return `
  <g transform="translate(${x} 40)">
    <rect width="560" height="600" rx="42" fill="${colors.background}"/>
    <g transform="translate(82 42) scale(0.77)">${logoMarkup(colors, { idSuffix: `-${mode}` })}</g>
    <text x="36" y="558" fill="${colors.label}" font-family="JetBrains Mono, monospace" font-size="22" font-weight="700" letter-spacing="1.5">${mode.toUpperCase()} MODE</text>
  </g>`;
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc">
  <title id="title">OpenE2EE shield in light and dark modes</title>
  <desc id="desc">Approved solid-color light and dark variants.</desc>
  <rect width="${width}" height="${height}" fill="#111418"/>${cards.join('')}
</svg>
`;
}

const svgDirectory = join(generatedBrand, 'svg');
const pngDirectory = join(generatedBrand, 'png');
await mkdir(svgDirectory, { recursive: true });
await mkdir(pngDirectory, { recursive: true });

for (const [mode, colors] of Object.entries(brand)) {
  const basename = `open-e2ee-shield-${mode}`;
  const svgPath = join(svgDirectory, `${basename}.svg`);
  const smallSvgPath = join(svgDirectory, `${basename}-small.svg`);
  await writeText(svgPath, standaloneSvg(mode, colors));
  await writeText(smallSvgPath, standaloneSvg(mode, colors, { small: true }));

  for (const size of [32, 64, 128, 512, 1024]) {
    const outputDirectory = join(pngDirectory, String(size));
    await mkdir(outputDirectory, { recursive: true });
    execFileSync('rsvg-convert', [
      '--width',
      String(size),
      '--height',
      String(size),
      '--output',
      join(outputDirectory, `${basename}.png`),
      size <= 64 ? smallSvgPath : svgPath,
    ]);
  }
}

await writeText(
  join(generatedBrand, 'open-e2ee-shield-adaptive.svg'),
  adaptiveSvg(),
);
await writeText(
  join(generatedBrand, 'open-e2ee-shield-adaptive-small.svg'),
  adaptiveSvg({ small: true }),
);
await writeText(
  join(generatedBrand, 'open-e2ee-shield-mode-sheet.svg'),
  modeSheetSvg(),
);
execFileSync('rsvg-convert', [
  '--width',
  '1240',
  '--height',
  '680',
  '--output',
  join(generatedBrand, 'open-e2ee-shield-mode-sheet.png'),
  join(generatedBrand, 'open-e2ee-shield-mode-sheet.svg'),
]);

await mkdir(join(generatedBrand, 'social'), { recursive: true });
await cp(
  join(root, 'brand', 'templates', 'social', 'open-e2ee-design-og.png'),
  join(generatedBrand, 'social', 'open-e2ee-design-og.png'),
);

await cp(generatedBrand, assetDistribution, { recursive: true });

const assetDigest = await digestDirectory(generatedBrand);
const assetFiles = await filesIn(generatedBrand);
const manifest = {
  package: packageJson.name,
  version: packageJson.version,
  sha256: assetDigest,
  files: assetFiles,
};
await writeText(
  join(generatedBrand, 'manifest.json'),
  JSON.stringify(manifest, null, 2),
);
await writeText(
  join(assetDistribution, 'manifest.json'),
  JSON.stringify(manifest, null, 2),
);

process.stdout.write(
  `Built ${packageJson.name} ${packageJson.version} with ${assetFiles.length} assets.\n`,
);
